title: Muhamed Javid Hussain - Technical Writer Portfolio
description: Senior Technical Writer specializing in user and developer documentation
author: Muhamed Javid Hussain
email: your-email@example.com
url: "https://javeed-writer.github.io"
baseurl: "/Portfolio"

# Build settings
markdown: kramdown
highlighter: rouge
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Navigation structure with icons
navigation:
  - name: "Home"
    link: "/"
    icon: "fas fa-home"
  - name: "About"
    link: "/about/"
    icon: "fas fa-user"
  - name: "Developer Guides"
    link: "/developer_guides/"
    icon: "fas fa-code"
  - name: "User Guides" 
    link: "/user-guides/"
    icon: "fas fa-book"
  - name: "Knowledge Base"
    link: "/knowledge_base/"
    icon: "fas fa-database"
  - name: "Contact"
    link: "/contact/"
    icon: "fas fa-envelope"

# Sidebar categories with descriptions
sidebar_categories:
  developer_guides:
    - name: "Pet Store API"
      link: "/developer_guides/rest_api_pet_store/"
      description: "Complete REST API documentation with examples"
    - name: "Content Archive API"
      link: "/developer_guides/graphql_api_content_archive/"
      description: "GraphQL API for content management"
    - name: "Card Ordering API"
      link: "/developer_guides/rest_api_ordering_a_new_card_zeta/"
      description: "Banking API for card operations"
    - name: "Content Filter API"
      link: "/developer_guides/graphql_api_content_filter/"
      description: "Content filtering and moderation API"
    - name: "Media Moderation API"
      link: "/developer_guides/graphql_api_bypass_media_moderation/"
      description: "Media moderation bypass permissions"
  
  user_guides:
    - name: "Add Money Feature"
      link: "/user-guides/zeta_add_money_guide/"
      description: "Digital wallet funding guide"
    - name: "SharePoint Online"
      link: "/user-guides/using_sharepoint_online/"
      description: "Collaboration platform setup"
    - name: "Control Panel Settings"
      link: "/user-guides/Configuring-the-Control-Panel-Settings/"
      description: "Administrative configuration guide"

# Skills configuration
skills:
  documentation_types:
    - "API Documentation"
    - "User Guides"
    - "Developer Docs"
    - "Release Notes"
    - "Knowledge Base"
  
  technical_skills:
    - "REST APIs"
    - "GraphQL"
    - "OpenAPI"
    - "Markdown"
    - "Git"
    - "Jekyll"
  
  tools_platforms:
    - "GitBook"
    - "Confluence"
    - "Notion"
    - "Figma"
    - "Postman"
    - "VS Code"
  
  industries:
    - "FinTech"
    - "SaaS"
    - "Enterprise"
    - "Developer Tools"

# Exclude from processing
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
