title: "Javeed-Writer Portfolio"
description: "A portfolio of technical writing, user guides, developer docs, and knowledge base articles."
theme: minima
baseurl: "" # leave it blank for user/organization site
markdown: kramdown

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-archives
  - jekyll-paginate
  - jekyll-toc

# Optional: Configure jekyll-toc defaults
toc:
  min_level: 2
  max_level: 3
  ordered_list: false
  no_toc_section_class: "no_toc_section"
  list_class: "toc-list"
  sublist_class: "toc-sublist"
  item_class: "toc-list-item"
